printWidth = 80
tabWidth = 2
useTabs = false
semi = true
singleQuote = true
jsxSingleQuote = true
trailingComma = "all"
bracketSpacing = true
jsxBracketSameLine = false
arrowParens = "avoid"
filepath = "*.js"
htmlWhitespaceSensitivity = "strict"
endOfLine = "lf"
overrides = [ { files = '*.css', options = { parser = 'css' } }]
